---
title: "Composition analysis"
author: "Yiluan Song"
date: "2023-09-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

Download NEON vegetation structure data. We already did this step for you.
```{r, eval = F}
# install neonUtilities - skip if already installed
install.packages("neonUtilities")
# load neonUtilities
library(neonUtilities)

dat <- loadByProduct(dpID="DP1.10098.001", 
                           site=c("BART"),
                           startdate="2017-01", 
                           enddate="2021-12")
write_rds(dat, "data.rds")
```


```{r}
dat <- read_rds("data.rds")

df_tree <- dat$vst_apparentindividual %>%
  arrange(desc(publicationDate)) %>%
  distinct(plotID, individualID, .keep_all = T) %>%
  filter(str_detect(plantStatus %>% tolower(), "live")) %>%
  select(plotID, individualID)
df_tree

df_tree_sp <- dat$vst_mappingandtagging %>%
  arrange(desc(publicationDate)) %>%
  distinct(individualID, plotID, .keep_all = T) %>%
  select(individualID, plotID, taxonID, scientificName) %>%
  filter(!is.na(taxonID)) %>%
  filter(taxonID != "2PLANT")
df_tree_sp

df_plot <- dat$vst_perplotperyear %>%
  arrange(desc(publicationDate)) %>%
  distinct(plotID, plotType, .keep_all = T) %>%
  select(plotID, plotType, nlcdClass, lon = decimalLongitude, lat = decimalLatitude)
df_plot
```

```{r}
df <- df_tree %>%
  inner_join(df_tree_sp,
    by = c("individualID", "plotID")
  ) %>%
  inner_join(df_plot,
    by = c("plotID")
  )
df
```


```{r}
df_comm <- df %>%
  group_by(plotID, plotType, nlcdClass, lat, lon, scientificName) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  spread(key = "scientificName", value = "count", fill = 0)
df_comm
```

```{r}
mat_comm <- df_comm %>%
  select(-plotID, -plotType, -nlcdClass, -lon, -lat) %>%
  as.matrix()
mat_comm
```

```{r}
set.seed(1)
mds_comm <- vegan::metaMDS(mat_comm, distant = "bray", k = 4, try = 100)
mds_comm
```

```{r}
mds_comm$stress
# https://uw.pressbooks.pub/appliedmultivariatestatistics/chapter/nmds/
vegan::stressplot(mds_comm)
```

```{r}
plot(mds_comm, type = "t")
```

```{r}
df_nmds_comm <- mds_comm %>%
  vegan::scores(display = "sites") %>%
  data.frame() %>%
  bind_cols(df_comm %>%
    select(plotID, plotType, nlcdClass))

df_nmds_sp <- mds_comm %>%
  vegan::scores(display = "species") %>%
  data.frame() %>%
  rownames_to_column(var = "species")

ggplot(df_nmds_comm, aes(x = NMDS1, y = NMDS2)) +
  geom_point() +
  ggrepel::geom_text_repel(data = df_nmds_sp, aes(NMDS1, NMDS2, label = species), color = "dark grey") +
  ggthemes::theme_few()
```

```{r}
ggplot(df_nmds_comm, aes(x = NMDS1, y = NMDS2, col = nlcdClass)) +
  geom_point() +
  stat_ellipse() +
  ggrepel::geom_text_repel(data = df_nmds_sp, aes(NMDS1, NMDS2, label = species), color = "dark grey") +
  ggthemes::theme_few() +
  coord_equal()

ggplot(df_nmds_comm, aes(x = NMDS3, y = NMDS4, col = nlcdClass)) +
  geom_point() +
  stat_ellipse() +
  ggrepel::geom_text_repel(data = df_nmds_sp, aes(NMDS1, NMDS2, label = species), color = "dark grey") +
  ggthemes::theme_few() +
  coord_equal()

ggplot(df_nmds_comm, aes(x = NMDS1, y = NMDS2, col = plotType)) +
  geom_point() +
  stat_ellipse() +
  ggrepel::geom_text_repel(data = df_nmds_sp, aes(NMDS1, NMDS2, label = species), color = "dark grey") +
  ggthemes::theme_few() +
  coord_equal()
```

```{r}
set.seed(1)
res_permanova <- vegan::adonis2(mat_comm ~ nlcdClass, data = df_comm, permutations = 9999)
res_permanova

set.seed(1)
res_permanova <- vegan::adonis2(mat_comm ~ plotType, data = df_comm, permutations = 9999)
res_permanova

set.seed(1)
res_permanova <- vegan::adonis2(mat_comm ~ nlcdClass * plotType, data = df_comm, permutations = 9999)
res_permanova
```



